version: '3.8'
services:
  etl:
    build: 
      context: ./etl
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./etl:/app
  
  # tests:
  #   image: data-research-jobs-tests:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./app:/app
  #     - ./tests:/app/tests
  #   command: ["pytest", "-v", "--reruns", "5", "--reruns-delay", "1"]



