# MIT License
#
# Copyright (c) 2022 Data Research Jobs Team, mohamedmohey2352@gmail.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

[indeed]
indeed_website = "http://www.indeed.com"

jobs_base_url = "https://%(country_code)s.indeed.com/jobs?q=%(job_title)s" 
job_base_url = "https://www.indeed.com/viewjob?jk=%(job_id)s"

company_base_url = "https://www.indeed.com/cmp/%(company_name)s"
countries_base_url = "https://www.indeed.com/worldwide"

[datastackjobs]
data_stack_jobs_url = "https://www.datastackjobs.com"
data_stack_jobs_sample_html = "Data-Engineering-Jobs-Research/app/etl/tests/resources/test_utils/data_stack_jobs_sample.html"

[company]
company_name = ''
company_location = ''
company_rating = ''
company_url = ''
country_name = ''

[job]

[job.job_basic_info]
job_title = ''
job_id = ''
job_url = ''
job_salary = ''

[job.job_more_info]
job_description = ''
job_benefits = ''
job_posted_date = ''

[skills]
programming_languages = ['java','c++','python','ruby','scala']

db_engines = ['oracle','mysql','microsoft sql server','postgresql','mongodb',
              'redis','ibm db2','elasticsearch','microsoft access','sqlite']

sql_and_no_sql = ['sql','nosql']

ingest_sass = ['stich','airbyte','fivetran','segment','rivery',
               'dataddo','datacoral','matillion','snowplow']

ingest_tech = ['google cloud pub/sub','apache storm','flink','amazon kinesis',
               'beam','materialize','kafka','beneath','spark','upsolver','confluent',]

object_storage = ['ibm cloud object storage','wasabi',
                  'seagate','minio','alibaba cloud','google cloud storage','zadara',
                  'hadoop','oracle cloud','amazon s3','firebase','cloudfiles',
                  'digitalocean','crowdstorage','swiftstack','lyve','ceph','purestorage'
                 ]
cloud_providers = ['aws','azure','google cloud','alibaba cloud','ibm cloud','salesforce',
                   'tencent cloud', 'oracle cloud', 'gcp']

metastore = ['hive','cloud dataproc','amazon glue','azure purview',
             'unity','cloudera','databricks']

open_table_formats = ['apache hudi','onehouse','iceberg','tabular','delta lake','databricks',
                      'delta lake', 'apache orc']

compute = ['databricks','ray','cloudwick','hadoop mapreduce','cloud Dataproc',
           'azure hdinsight','akka platform','dask','ascend.io']

analytics_engine = ['databricks','snowflake','dremio','amazon athena',
                    'startree','pentaho','qubole','clickhouse','druid',
                    'firebolt','starburst','google big query','amazon redshift',
                    'pinot','cloudera impala'
                    ]

data_viz_tools = ['tableau', 'power bi','excel', 'ibm_watson']
    
git_for_data = ['lakefs','project nessie']

orcherstration = ['airflow','flyte','oozie','dagster','astronomer']

mlops_end_to_end = ['google colab','octoml','abacus.ai','metaflow',
                    'disdat','verta','cnvrg.io','mlflow','snorkel',
                    'seldon','hugging face', 'datarobot','vertex.ai',
                    'w&b','hobsworks','kubeflow','google data studio',
                    'clear|ml','valohai','neptune.ai','domino',
                    'amazon segemaker','floydhub','iguazio','hydrosphere.io',
                    'zenlml','michelangelo','kedro','comet','h2o.io'
                    ]

data_centric_ai_ml = ['graviti','activeloop','DAGsHub','DVC','Pachyderm']

analytics_workflow = ['dataform','dbt','querybook','databricks']

ml_observability = ['deep checks','mona','superwise','fiddler','arize',
                    'whylabs','arthur','galileo','robust intelligence',
                    'gantry','tuera'
                    ]

notebooks = ['jupyter','hex','apache zeppelin','deepnote','count','noteable']

feature_stores = ['tecton','feast','ragso','vertex.ai','hopsworks','scribbledata',
                  'molecula','kaskada']

discovery_governance = ['marquez','bigid','collibra','magda',
                        'apache atlas','meta','amundsen','okera',
                        'alation','data.world','ckan','metacat','amazon glue',
                        'ckan','immuta','atlan','datahub','ibm watson']

devops = ['git','github','bitbucket','gitlab','docker','jenkins','kubernetes',
          'ansible','terraform','maven','chef','gradle','jira','puppet','saltstack',
          'junit']
automation = ['katalon studio','selenium','uft one','soap ui','testcomplete',
              'cucumber']